volumes:
    keys_volume:

services:
    sql_server:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            SA_PASSWORD: "GLvd8whQnA"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        volumes:
            - ./data:/data # This will make the .bak file available inside the container
            - ./scripts:/scripts # This directory contains the script to restore the database
        command:
            - /bin/bash
            - -c
            - |
                /opt/mssql/bin/sqlservr & # Start SQL Server in the background
                sleep 30 # Give SQL Server some time to start
                /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P GLvd8whQnA -i /scripts/restore.sql
                tail -f /var/opt/mssql/log/errorlog # Keep the SQL Server log output running

    webapp:
        build:
            context: .
            dockerfile: Dockerfile.backend
        volumes:
            - ./data:/app/data
            - keys_volume:/keys
        ports:
            - "5140:5140"
            - "7232:7232"
        depends_on:
            - sql_server
        environment:
            - TwitterCloneConnectionString=Server=sql_server;Initial Catalog=TwitterClone;Persist Security Info=True;User ID=SA;Password=GLvd8whQnA;MultipleActiveResultSets=True
            - SecretKeyForJwtToken=5cf148b7-cb19-4186-9078-a453d8e9556a
            - ValidIssuer=worsham.twitter.clone.angular
            - ValidAudience=worsham.twitter.clone.angular.ClientApp
