// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace brian.worsham.twitter.clone2.Models
{
    public partial class Likes
    {
        [Key]
        public int Id { get; set; }
        public int LikedTweetId { get; set; }
        [Required]
        [StringLength(450)]
        public string UserThatLikedTweetId { get; set; }

        [ForeignKey("LikedTweetId")]
        [InverseProperty("Likes")]
        public virtual Tweets LikedTweet { get; set; }
        [ForeignKey("UserThatLikedTweetId")]
        [InverseProperty("Likes")]
        public virtual AspNetUsers UserThatLikedTweet { get; set; }
    }
}