// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace worsham.twitter.clone.Models.EntityModels
{
    public partial class Tweets
    {
        public Tweets()
        {
            Comments = new HashSet<Comments>();
            Likes = new HashSet<Likes>();
            ReTweets = new HashSet<ReTweets>();
        }

        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(280)]
        [Unicode(false)]
        public string Content { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreationDateTime { get; set; }
        public int TweeterId { get; set; }

        [ForeignKey("TweeterId")]
        [InverseProperty("Tweets")]
        public virtual Users Tweeter { get; set; }
        [InverseProperty("OriginalTweet")]
        public virtual ICollection<Comments> Comments { get; set; }
        [InverseProperty("LikedTweet")]
        public virtual ICollection<Likes> Likes { get; set; }
        [InverseProperty("OriginalTweet")]
        public virtual ICollection<ReTweets> ReTweets { get; set; }
    }
}